services:
  db:
    image: postgres:15
    container_name: products_db

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  etl:
    build: .
    container_name: products_etl

    depends_on:
      db:
        condition: service_healthy

    env_file:
      - .env

    command: python etl/download_products.py
 
  app:
    build: .
    container_name: products_dashboard

    depends_on:
      db:
        condition: service_healthy

    env_file:
      - .env

    ports:
      - "8502:8501"

    command: streamlit run app/app.py --server.address=0.0.0.0

volumes:
  postgres_data:
